services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - product-network
      # - microservice-network
    environment:
      - USER_SERVICE_URL=http://user-service:8003/api/v1

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - product-network

networks:
  product-network:
    driver: bridge


volumes:
  mongodb_data: