apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: shopverce
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: swapno/order-service:latest
          ports:
            - containerPort: 8001
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ORDER_MONGODB_URI
            - name: MONGODB_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ORDER_MONGODB_DB
            - name: API_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: API_PREFIX
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DEBUG
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ORDER_SERVICE_PORT
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SECRET_KEY
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USER_SERVICE_URL
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PRODUCT_SERVICE_URL
            - name: INVENTORY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: INVENTORY_SERVICE_URL
            - name: MAX_RETRIES
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MAX_RETRIES
            - name: RETRY_DELAY
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RETRY_DELAY
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: shopverce
spec:
  selector:
    app: order-service
  ports:
    - port: 8001
      targetPort: 8001
  type: ClusterIP
