apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-inventory
  namespace: ecommerce
  labels:
    app: postgres-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-inventory
  template:
    metadata:
      labels:
        app: postgres-inventory
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "inventory_db"
          volumeMounts:
            - name: postgres-inventory-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - inventory_db
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: postgres-inventory-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-inventory
  namespace: ecommerce
spec:
  selector:
    app: postgres-inventory
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
